changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - breaking
        - breaking-change
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - bugfix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Security
      labels:
        - security
    - title: Miscellaneous
      labels:
        - chore
        - internal
